# Generated by Django 4.2.7 on 2023-11-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
